# Comparisons with the R reference implementations. Reference values are generated by
# test/validation/synth/generate_references.R (package versions in
# reference_versions.csv).

_refrow(df, col, val) = df[df[!, col] .== val, :]
_parse_index(s) = parse.(Int, split(s, ';'))

@testset "synthdid: California Proposition 99" begin
    df = load_prop99()
    est = read_ref_csv("sdid_prop99_estimates.csv")
    wref = read_ref_csv("sdid_prop99_weights.csv")
    cref = read_ref_csv("sdid_prop99_effect_curves.csv")
    draws = read_ref_csv("sdid_prop99_placebo_draws.csv")
    B = mc_reps(4000, 1000)
    for m in ("sdid", "sc", "did")
        r = synthetic_did(df, :PacksPerCapita, :treated, :State, :Year; method=Symbol(m),
                          se_method=:placebo, replications=B, rng=StableRNG(99))
        e = _refrow(est, :estimator, m)
        @test r.att ≈ e.estimate[1] rtol = 1e-8
        c = r.cohorts[1]
        @test c.opts.zeta_omega ≈ e.zeta_omega[1] rtol = 1e-10
        @test c.noise_level ≈ e.noise_level[1] rtol = 1e-10
        w = _refrow(_refrow(wref, :estimator, m), :type, "omega")
        @test synth_weights(r).unit == w.name
        @test synth_weights(r).weight ≈ w.weight atol = 1e-8
        l = _refrow(_refrow(wref, :estimator, m), :type, "lambda")
        @test synth_time_weights(r).weight ≈ l.weight atol = 1e-8
        g = synth_gaps(r)
        @test g.gap[g.post] ≈ _refrow(cref, :estimator, m).effect atol = 1e-6
        # identical placebo permutations give identical replicate estimates
        p = r.panel
        for d in eachrow(_refrow(draws, :estimator, m))
            ind = _parse_index(d.index)
            theta = DrSnow._sc_sdid_theta(p.Y, nothing, :none, r.cohorts, ind[1:37],
                                          ind[38:38], [20])
            @test theta ≈ d.theta rtol = 1e-7
        end
        # placebo SE: Monte Carlo error ≈ 2.2% (R, 1000 draws) and ≤ 2.2% (Julia)
        @test r.se / e.se_placebo_1000[1] ≈ 1 atol = 0.12
    end
end

@testset "synthdid: simulated block design (N1 = 5, covariates)" begin
    sim = read_ref_csv("sdid_sim_block.csv")
    est = read_ref_csv("sdid_sim_estimates.csv")
    wref = read_ref_csv("sdid_sim_weights.csv")
    bdraws = read_ref_csv("sdid_sim_bootstrap_draws.csv")
    B = mc_reps(3000, 600)
    for m in ("sdid", "sc", "did", "sdid_cov")
        method = m == "sdid_cov" ? :sdid : Symbol(m)
        covs = m == "sdid_cov" ? [:x1, :x2] : Symbol[]
        e = _refrow(est, :estimator, m)
        rj = synthetic_did(sim, :y, :treated, :unit, :time; method=method,
                           covariates=covs, se_method=:jackknife)
        @test rj.att ≈ e.estimate[1] rtol = 1e-7
        @test rj.se ≈ e.se_jackknife[1] rtol = 1e-6
        w = _refrow(_refrow(wref, :estimator, m), :type, "omega")
        @test synth_weights(rj).weight ≈ w.weight atol = 1e-7
        if m == "sdid_cov"
            @test rj.cohorts[1].beta ≈ [e.beta1[1], e.beta2[1]] rtol = 1e-6
        end
        p = rj.panel
        X = m == "sdid_cov" ? DrSnow._sc_complete_covariates(p, "test") : nothing
        cm = m == "sdid_cov" ? :optimized : :none
        for d in eachrow(_refrow(bdraws, :estimator, m))
            ind = sort(_parse_index(d.index))
            ctrl = ind[ind .<= 35]
            trt = ind[ind .> 35]
            theta = DrSnow._sc_sdid_theta(p.Y, X, cm, rj.cohorts, ctrl, trt,
                                          p.adoption[trt])
            @test theta ≈ d.theta rtol = 1e-6
        end
        rb = synthetic_did(sim, :y, :treated, :unit, :time; method=method,
                           covariates=covs, se_method=:bootstrap, replications=B,
                           rng=StableRNG(7))
        @test rb.se / e.se_bootstrap_1000[1] ≈ 1 atol = 0.13
        rp = synthetic_did(sim, :y, :treated, :unit, :time; method=method,
                           covariates=covs, se_method=:placebo, replications=B,
                           rng=StableRNG(8))
        @test rp.se / e.se_placebo_1000[1] ≈ 1 atol = 0.13
    end
end

@testset "synthdid: staggered adoption (cohort-wise synthdid in R)" begin
    stag = read_ref_csv("sdid_sim_staggered.csv")
    coh = read_ref_csv("sdid_sim_staggered_cohorts.csv")
    r = synthetic_did(stag, :y, :treated, :unit, :time; se_method=:none)
    c = synth_cohorts(r)
    @test c.adoption == coh.adoption
    @test c.n_treated == coh.n_treated
    @test c.estimate ≈ coh.estimate rtol = 1e-8
    @test c.weight ≈ coh.weight
    @test r.att ≈ coh.att[1] rtol = 1e-8
end

@testset "augsynth: ridge ASCM, SCM, conformal inference" begin
    df = load_prop99()
    summ = read_ref_csv("ascm_prop99_summary.csv")
    wref = read_ref_csv("ascm_prop99_weights.csv")
    aref = read_ref_csv("ascm_prop99_att.csv")
    cvref = read_ref_csv("ascm_prop99_cv.csv")
    models = Dict("ridge" => (ridge=true, fixed_effects=false, lambda=nothing),
                  "scm" => (ridge=false, fixed_effects=false, lambda=nothing),
                  "ridge_fe" => (ridge=true, fixed_effects=true, lambda=nothing),
                  "ridge_fixed" => (ridge=true, fixed_effects=false, lambda=1e4))
    fits = Dict{String,Any}()
    for (name, kw) in models
        r = augmented_synthetic_control(df, :PacksPerCapita, :treated, :State, :Year;
                                        se_method=:jackknife, kw...)
        fits[name] = r
        s = _refrow(summ, :model, name)
        if kw.ridge
            @test r.lambda ≈ s.lambda[1] rtol = 1e-8
        end
        @test synth_weights(r).weight ≈ _refrow(wref, :model, name).weight atol = 1e-5
        @test r.att_path ≈ _refrow(aref, :model, name).att atol = 1e-4
        @test r.att ≈ s.average_att[1] atol = 1e-5
        @test r.se ≈ s.se_jackknife[1] rtol = 1e-4
    end
    cv = fits["ridge"].cv
    @test cv.lambda ≈ cvref.lambda rtol = 1e-10
    @test cv.error ≈ cvref.error rtol = 1e-5
    @test cv.error_se ≈ cvref.error_se rtol = 1e-5

    conf = read_ref_csv("ascm_prop99_conformal_block.csv")
    joint = read_ref_csv("ascm_prop99_conformal_block_joint.csv")
    for name in ("ridge", "scm")
        ci = synth_conformal_inference(fits[name]; type=:block)
        ref = _refrow(conf, :model, name)
        ref = ref[.!ismissing.(ref.p_value), :]
        @test ci.per_period.p_value ≈ ref.p_value atol = 1e-12
        @test collect(skipmissing(ci.per_period.lower)) ≈ ref.lower atol = 1e-4
        @test collect(skipmissing(ci.per_period.upper)) ≈ ref.upper atol = 1e-4
        @test all(ci.per_period.truncated)   # 1/(T0+1) = 0.05: nothing is rejected
        @test ci.joint.pvalue ≈ _refrow(joint, :model, name).p_value[1] atol = 1e-12
    end
end

@testset "Synth: Basque Country (Abadie & Gardeazabal 2003)" begin
    bq = read_ref_csv("basque.csv")
    bq = bq[bq.regionno .!= 1, :]
    bq.treated = Int.((bq.regionno .== 17) .& (bq.year .>= 1970))
    preds = Symbol.(["school.illit", "school.prim", "school.med", "school.high",
                     "school.post.high", "invest"])
    secs = ["sec.agriculture", "sec.energy", "sec.industry", "sec.construction",
            "sec.services.venta", "sec.services.nonventa"]
    sp = vcat([Symbol("gdpcap") => 1960:1969], [Symbol(s) => 1961:2:1969 for s in secs],
              [Symbol("popdens") => [1969]])
    vref = read_ref_csv("adh_basque_v.csv")
    wref = read_ref_csv("adh_basque_w.csv")
    lref = read_ref_csv("adh_basque_loss.csv")
    gref = read_ref_csv("adh_basque_gaps.csv")
    x0ref = read_ref_csv("adh_basque_X0.csv")
    kw = (predictors=preds, predictor_periods=1964:1969, special_predictors=sp,
          fit_periods=1960:1969, placebo=false)
    # Synth's V: the inner problem has a unique solution, so W must agree
    rv = synthetic_control(bq, :gdpcap, :treated, :regionno, :year; kw..., v=vref.v)
    @test rv.predictor_balance.treated ≈ vref.treated rtol = 1e-10
    X0 = Matrix{Float64}(x0ref[:, 2:end])
    @test size(X0) == (14, 16)
    @test rv.predictor_balance.donor_mean ≈ vec(mean(X0; dims=2)) rtol = 1e-10
    @test rv.predictor_balance.synthetic ≈ X0 * wref.w rtol = 1e-4
    @test rv.weights ≈ wref.w atol = 1e-5
    @test rv.loss_w ≈ lref.loss_w[1] rtol = 1e-4
    @test synth_gaps(rv).gap ≈ gref.gap atol = 1e-4
    # nested optimisation from Synth's starting values: same or lower loss
    r = synthetic_control(bq, :gdpcap, :treated, :regionno, :year; kw...)
    @test r.loss_v <= lref.loss_v[1] * (1 + 1e-4)
    @test r.weights ≈ wref.w atol = 1e-3
    @test synth_gaps(r).gap ≈ gref.gap atol = 1e-3
    @test r.att ≈ mean(gref.gap[gref.year .>= 1970]) atol = 1e-3
end

@testset "MCPanel: MC-NNM on Proposition 99" begin
    df = load_prop99()
    ref = read_ref_csv("mcnnm_prop99.csv")
    fitted = read_ref_csv("mcnnm_prop99_fitted.csv")
    r = matrix_completion(df, :PacksPerCapita, :treated, :State, :Year;
                          lambda=ref.lambda[1], se_method=:none)
    @test r.att ≈ ref.att[1] rtol = 1e-3
    @test r.rank == ref.rank[1]
    p = r.panel
    idx = Dict(u => i for (i, u) in enumerate(p.units))
    yhat = [r.Y0hat[idx[f.unit], f.time - 1969] for f in eachrow(fitted)]
    @test maximum(abs.(yhat .- fitted.yhat)) < 0.05
    r2 = matrix_completion(df, :PacksPerCapita, :treated, :State, :Year;
                           lambda=ref.lambda[2], se_method=:none)
    @test r2.att ≈ ref.att[2] rtol = 1e-3
    # cross-validated λ: folds are random (different generators), so only the order
    # of magnitude of λ and the ATT are compared
    rc = matrix_completion(df, :PacksPerCapita, :treated, :State, :Year;
                           se_method=:none, rng=StableRNG(2024))
    @test 0.1 < rc.lambda / ref.lambda[1] < 10
    @test abs(rc.att - ref.att[1]) < 1.5
end
