# Reference values for DrSnow's randomization-inference module.
#
# Regenerate with (from the repository root):
#   R_LIBS_USER=<lib with ri2, randomizr> Rscript test/validation/ri/make_ri2_reference.R
# Writes test/validation/ri/ri2_reference.jl (Julia literal data + reference values).
# Every design below is small enough that ri2 enumerates all assignments exactly
# (sims >= number of permutations), so the p-values are exact.

suppressPackageStartupMessages({library(ri2); library(randomizr)})
out <- "test/validation/ri/ri2_reference.jl"
fmt <- function(x) {
  if (is.logical(x)) x <- as.integer(x)
  paste0("[", paste(sprintf("%.17g", x), collapse = ", "), "]")
}
num <- function(x) sprintf("%.17g", x)
p2 <- function(r, p = "two-tailed") summary(r, p = p)[1, 3]
lines <- c("# Generated by make_ri2_reference.R; do not edit by hand.",
           paste0("# R ", getRversion(), ", ri2 ", packageVersion("ri2"),
                  ", randomizr ", packageVersion("randomizr")),
           "const RI2_REF = Dict{Symbol,Any}()")
add <- function(name, fields) {
  body <- paste(sprintf("%s = %s", names(fields), unlist(fields)), collapse = ",\n    ")
  lines <<- c(lines, sprintf("RI2_REF[:%s] = (\n    %s,\n)", name, body))
}
S <- 100000

# 1. Complete randomization, N = 10, m = 5 (252 assignments)
set.seed(20260927)
N <- 10
Z <- complete_ra(N, m = 5); Y <- rnorm(N) + 0.8 * Z
dat <- data.frame(Y, Z); dec <- declare_ra(N = N, m = 5)
r0 <- conduct_ri(Y ~ Z, declaration = dec, data = dat, sims = S)
rh <- conduct_ri(Y ~ Z, declaration = dec, data = dat, sims = S, sharp_hypothesis = 0.7)
rs <- conduct_ri(Y ~ Z, declaration = dec, data = dat, sims = S, studentize = TRUE)
add("complete", list(y = fmt(Y), z = fmt(Z), n_perm = num(obtain_num_permutations(dec)),
    estimate = num(summary(r0)[1, 2]), p_two = num(p2(r0)), p_upper = num(p2(r0, "upper")),
    p_lower = num(p2(r0, "lower")), p_two_h07 = num(p2(rh)),
    p_upper_h07 = num(p2(rh, "upper")), t_stud = num(summary(rs)[1, 2]),
    p_two_stud = num(p2(rs))))

# 2. Blocked, equal blocks (3 x 4, 2 treated each; 216 assignments)
set.seed(11)
b <- rep(1:3, each = 4)
Z <- block_ra(blocks = b, block_m = c(2, 2, 2)); Y <- rnorm(12) + b / 2 + 0.5 * Z
dat <- data.frame(Y, Z, b); dec <- declare_ra(blocks = b, block_m = c(2, 2, 2))
r0 <- conduct_ri(Y ~ Z, declaration = dec, data = dat, sims = S)
add("blocked", list(y = fmt(Y), z = fmt(Z), block = fmt(b),
    n_perm = num(obtain_num_permutations(dec)), estimate = num(summary(r0)[1, 2]),
    p_two = num(p2(r0))))

# 3. Blocked, unequal blocks (4, 6, 8 units; 2, 3, 3 treated; 6720 assignments) with
#    the block-size-weighted difference in means as test statistic.
set.seed(12)
b <- rep(1:3, times = c(4, 6, 8))
Z <- block_ra(blocks = b, block_m = c(2, 3, 3)); Y <- rexp(18) + b + 0.4 * Z
dat <- data.frame(Y, Z, b); dec <- declare_ra(blocks = b, block_m = c(2, 3, 3))
wdm <- function(d) {
  s <- split(d, d$b)
  sum(sapply(s, function(x) nrow(x) * (mean(x$Y[x$Z == 1]) - mean(x$Y[x$Z == 0])))) /
    nrow(d)
}
r0 <- conduct_ri(test_function = wdm, declaration = dec, assignment = "Z",
                 outcome = "Y", data = dat, sims = S)
rh <- conduct_ri(test_function = wdm, declaration = dec, assignment = "Z",
                 outcome = "Y", data = dat, sims = S, sharp_hypothesis = -0.3)
add("blocked_unequal", list(y = fmt(Y), z = fmt(Z), block = fmt(b),
    n_perm = num(obtain_num_permutations(dec)), estimate = num(summary(r0)[1, 2]),
    p_two = num(p2(r0)), p_upper = num(p2(r0, "upper")),
    estimate_h = num(summary(rh)[1, 2]), p_two_h = num(p2(rh)),
    p_upper_h = num(p2(rh, "upper"))))

# 4. Cluster randomization: 8 clusters of sizes 2-4, 3 treated (56 assignments)
set.seed(13)
cl <- rep(1:8, times = c(2, 3, 4, 2, 3, 4, 2, 3))
Z <- cluster_ra(clusters = cl, m = 3); Y <- rnorm(length(cl)) + rnorm(8)[cl] + 0.3 * Z
dat <- data.frame(Y, Z, cl); dec <- declare_ra(clusters = cl, m = 3)
r0 <- conduct_ri(Y ~ Z, declaration = dec, data = dat, sims = S)
add("cluster", list(y = fmt(Y), z = fmt(Z), cluster = fmt(cl),
    n_perm = num(obtain_num_permutations(dec)), estimate = num(summary(r0)[1, 2]),
    p_two = num(p2(r0)), p_lower = num(p2(r0, "lower"))))

# 5. Blocked cluster randomization: 2 blocks x 5 clusters, 2 treated per block
#    (100 assignments), block-size-weighted difference in means.
set.seed(14)
cl <- rep(1:10, times = c(2, 3, 2, 4, 3, 2, 2, 3, 4, 2))
bl <- ifelse(cl <= 5, 1, 2)
Z <- block_and_cluster_ra(blocks = bl, clusters = cl, block_m = c(2, 2))
Y <- rnorm(length(cl)) + bl + 0.5 * Z
dat <- data.frame(Y, Z, b = bl, cl)
dec <- declare_ra(blocks = bl, clusters = cl, block_m = c(2, 2))
r0 <- conduct_ri(test_function = wdm, declaration = dec, assignment = "Z",
                 outcome = "Y", data = dat, sims = S)
add("block_cluster", list(y = fmt(Y), z = fmt(Z), block = fmt(bl), cluster = fmt(cl),
    n_perm = num(obtain_num_permutations(dec)), estimate = num(summary(r0)[1, 2]),
    p_two = num(p2(r0))))

# 6. Wilcoxon rank-sum: exact p-value, Hodges-Lehmann estimate and exact CI
set.seed(15)
Z <- complete_ra(12, m = 6); Y <- round(rnorm(12) + 1.0 * Z, 6)
w <- wilcox.test(Y[Z == 1], Y[Z == 0], exact = TRUE, conf.int = TRUE, conf.level = 0.9)
wg <- wilcox.test(Y[Z == 1], Y[Z == 0], exact = TRUE, alternative = "greater")
add("wilcoxon", list(y = fmt(Y), z = fmt(Z), p_two = num(w$p.value),
    p_greater = num(wg$p.value), hl = num(w$estimate), ci_lower = num(w$conf.int[1]),
    ci_upper = num(w$conf.int[2]), ci_level = num(0.9)))

# 7. p.adjust
p <- c(0.001, 0.012, 0.04, 0.041, 0.2, 0.5, 0.03, 0.9)
add("padjust", list(p = fmt(p), holm = fmt(p.adjust(p, "holm")),
    bh = fmt(p.adjust(p, "BH"))))

writeLines(lines, out)
cat("wrote", out, "\n")
