# Comparison with R reference implementations (values in test/validation/did,
# generated by generate_did_references.R).
#
# Point estimates must agree to ~1e-8. Standard errors of influence-function
# estimators must agree to ~1e-7 (relative). Cluster-robust regression standard errors
# differ from fixest by a constant factor of ≈1.0002 because FixedEffectModels counts
# one more parameter in its (n-1)/(n-K) small-sample correction; they are compared with
# rtol = 1e-3.

@testset "R reference comparisons" begin
    mp = did_read_csv("mpdta.csv")

    @testset "Sant'Anna–Zhao vs DRDID" begin
        ref = did_read_csv("r_drdid.csv")
        lal = did_read_csv("lalonde_panel.csv")
        rc = did_read_csv("sim_rc.csv")
        xs = [:age, :educ, :black, :married, :nodegree, :hisp, :re74]
        mmap = Dict("dr_imp" => :dr_improved, "dr" => :dr, "reg" => :reg,
                    "std_ipw" => :ipw, "ipw" => :ipw_unnormalized)
        for r in eachrow(ref)
            m = mmap[r.method]
            w = r.weighted == 1 ? :w : nothing
            est = if r.data == "rc"
                did_drdid(rc, :y, :d, nothing, :post; method=m, weights=w,
                          covariates=[:x1, :x2, :x3, :x4])
            else
                did_drdid(lal, :re, :experimental, :id, :year; method=m, weights=w,
                          covariates=r.data == "panel" ? xs : Symbol[])
            end
            @test coef(est)[1] ≈ r.att rtol = 1e-7
            @test stderror(est)[1] ≈ r.se rtol = 1e-7
            @test dof_residual(est) == Inf
        end
    end

    @testset "Callaway–Sant'Anna vs did::att_gt / aggte" begin
        gt = did_read_csv("r_att_gt.csv")
        ag = did_read_csv("r_aggte.csv")
        scen = Dict(
            "S1" => (Symbol[], :never_treated, :dr, :varying, 0, nothing),
            "S2" => ([:lpop], :never_treated, :dr, :varying, 0, nothing),
            "S3" => ([:lpop], :not_yet_treated, :dr, :varying, 0, nothing),
            "S4" => ([:lpop], :never_treated, :ipw, :varying, 0, nothing),
            "S5" => ([:lpop], :never_treated, :reg, :varying, 0, nothing),
            "S6" => (Symbol[], :never_treated, :dr, :universal, 0, nothing),
            "S7" => ([:lpop], :not_yet_treated, :dr, :varying, 1, nothing),
            "S8" => ([:lpop], :never_treated, :dr, :varying, 0, :w),
            "S9" => ([:lpop], :not_yet_treated, :reg, :universal, 0, nothing))
        aggs = (("simple", :simple, (;)), ("group", :group, (;)),
                ("dynamic", :dynamic, (;)), ("calendar", :calendar, (;)),
                ("dynamic_bal1", :dynamic, (; balance_e=1)),
                ("dynamic_win", :dynamic, (; min_e=-2, max_e=2)))
        for s in sort!(collect(keys(scen)))
            cov, cg, m, bp, a, w = scen[s]
            cs = if a > 0
                @test_logs (:warn, r"already treated") match_mode = :any begin
                    did_callaway_santanna(mp, :lemp, FirstTreated(:first_treat),
                        :countyreal, :year; covariates=cov, control_group=cg, method=m,
                        base_period=bp, anticipation=a, weights=w, bootstrap=false)
                end
            else
                did_callaway_santanna(mp, :lemp, FirstTreated(:first_treat), :countyreal,
                    :year; covariates=cov, control_group=cg, method=m, base_period=bp,
                    anticipation=a, weights=w, bootstrap=false)
            end
            se = stderror(cs)
            pos = Dict((cs.periods[g], cs.periods[t]) => k
                       for (k, (g, t)) in enumerate(zip(cs.groups, cs.times)))
            r = gt[gt.scenario .== s, :]
            nref = 0
            for row in eachrow(r)
                k = get(pos, (row.group, row.t), 0)
                if k == 0   # universal-base reference cell: ATT ≡ 0, not reported
                    @test bp === :universal && row.att == 0
                    continue
                end
                nref += 1
                @test cs.coef[k] ≈ row.att atol = 1e-9
                @test se[k] ≈ row.se rtol = 1e-7
            end
            @test nref == length(cs.coef)
            for (an, typ, kw) in aggs
                agg = aggregate_att(cs, typ; bootstrap=false, kw...)
                vals = Dict{String,Tuple{Float64,Float64}}()
                if agg isa EventStudyEstimate
                    ov = agg.details.overall
                    vals["overall"] = (coef(ov)[1], stderror(ov)[1])
                    for (e, b, sd) in zip(relative_periods(agg), coef(agg), stderror(agg))
                        vals[string(e)] = (b, sd)
                    end
                else
                    vals["overall"] = (coef(agg)[1], stderror(agg)[1])
                    for (l, b, sd) in zip(agg.labels, coef(agg)[2:end],
                                          stderror(agg)[2:end])
                        vals[string(Int(l))] = (b, sd)
                    end
                end
                rr = ag[(ag.scenario .== s) .& (ag.agg .== an), :]
                for row in eachrow(rr)
                    lbl = row.label == "overall" ? "overall" :
                          string(Int(parse(Float64, row.label)))
                    if !haskey(vals, lbl)   # universal reference event time
                        @test row.att == 0 && isnan(row.se)
                        continue
                    end
                    b, sd = vals[lbl]
                    @test b ≈ row.att atol = 1e-9
                    @test sd ≈ row.se rtol = 1e-7
                end
            end
        end
    end

    @testset "Callaway–Sant'Anna, repeated cross-sections, vs did (panel = FALSE)" begin
        gt = did_read_csv("r_att_gt_rc.csv")
        ag = did_read_csv("r_aggte_rc.csv")
        scen = Dict("R1" => (Symbol[], :never_treated, :dr, :varying),
                    "R2" => ([:lpop], :not_yet_treated, :dr, :varying),
                    "R3" => ([:lpop], :never_treated, :reg, :universal),
                    "R4" => ([:lpop], :never_treated, :ipw, :varying))
        for s in sort!(collect(keys(scen)))
            cov, cg, m, bp = scen[s]
            cs = did_callaway_santanna(mp, :lemp, FirstTreated(:first_treat), nothing,
                                       :year; covariates=cov, control_group=cg, method=m,
                                       base_period=bp, bootstrap=false)
            @test nobs(cs) == nrow(mp)
            se = stderror(cs)
            pos = Dict((cs.periods[g], cs.periods[t]) => k
                       for (k, (g, t)) in enumerate(zip(cs.groups, cs.times)))
            for row in eachrow(gt[gt.scenario .== s, :])
                k = get(pos, (row.group, row.t), 0)
                if k == 0
                    @test bp === :universal && row.att == 0
                    continue
                end
                @test cs.coef[k] ≈ row.att atol = 1e-9
                @test se[k] ≈ row.se rtol = 1e-7
            end
            for typ in (:simple, :group, :dynamic, :calendar)
                a = aggregate_att(cs, typ; bootstrap=false)
                vals = Dict{String,Tuple{Float64,Float64}}()
                if a isa EventStudyEstimate
                    vals["overall"] = (coef(a.details.overall)[1],
                                       stderror(a.details.overall)[1])
                    for (e, b, sd) in zip(relative_periods(a), coef(a), stderror(a))
                        vals[string(e)] = (b, sd)
                    end
                else
                    vals["overall"] = (coef(a)[1], stderror(a)[1])
                    for (l, b, sd) in zip(a.labels, coef(a)[2:end], stderror(a)[2:end])
                        vals[string(Int(l))] = (b, sd)
                    end
                end
                for row in eachrow(ag[(ag.scenario .== s) .& (ag.agg .== string(typ)), :])
                    lbl = row.label == "overall" ? "overall" :
                          string(Int(parse(Float64, row.label)))
                    if !haskey(vals, lbl)
                        @test row.att == 0
                        continue
                    end
                    @test vals[lbl][1] ≈ row.att atol = 1e-9
                    @test vals[lbl][2] ≈ row.se rtol = 1e-7
                end
            end
        end
    end

    @testset "TWFE and binned event study vs fixest" begin
        tw = did_read_csv("r_twfe.csv")
        r = did_twfe(mp, :lemp, :d, :countyreal, :year; warn_heterogeneity=false)
        @test coef(r)[1] ≈ tw.estimate[1] atol = 1e-12
        @test stderror(r)[1] ≈ tw.se[1] rtol = 1e-3
        @test dof_residual(r) == 499
        rw = did_twfe(mp, :lemp, :d, :countyreal, :year; weights=:w,
                      warn_heterogeneity=false)
        @test coef(rw)[1] ≈ tw.estimate[2] atol = 1e-12
        @test stderror(rw)[1] ≈ tw.se[2] rtol = 1e-3
        es = @test_logs (:warn, r"treatment cohorts") event_study(mp, :lemp, :d,
            :countyreal, :year; estimator=:twfe, max_pre=3, max_post=2)
        esr = tw[tw.model .== "es_bin_m3_p2", :]
        @test relative_periods(es) == [-3, -2, 0, 1, 2]
        @test coefnames(es) == ["e<=-3", "e=-2", "e=0", "e=1", "e>=2"]
        @test coef(es) ≈ esr.estimate atol = 1e-12
        @test stderror(es) ≈ esr.se rtol = 1e-3
    end

    @testset "Sun–Abraham vs fixest::sunab" begin
        sa = did_read_csv("r_sunab.csv")
        s = did_sun_abraham(mp, :lemp, FirstTreated(:first_treat), :countyreal, :year)
        per = sa[sa.term .!= "ATT", :]
        @test relative_periods(s) == Int.(parse.(Float64, per.term))
        @test coef(s) ≈ per.estimate atol = 1e-12
        @test stderror(s) ≈ per.se rtol = 1e-3
        @test coef(s.details.att)[1] ≈ sa.estimate[end] atol = 1e-12
        @test stderror(s.details.att)[1] ≈ sa.se[end] rtol = 1e-3
        # Full covariance: aggregating fixest's cohort-level covariance with DrSnow's
        # cohort-share weights reproduces vcov(s) (up to the FEM/fixest scalar).
        Vr = did_read_csv("r_sunab_vcov.csv")
        ce = s.details.cohort_effects
        ord = map(Vr.term) do t
            m = match(r"(-?\d+):cohort::(\d+)", t)
            e, g = parse(Int, m[1]), parse(Float64, m[2])
            findfirst(i -> ce.e[i] == e && ce.cohort[i] == g, 1:nrow(ce))
        end
        Vcell = zeros(nrow(ce), nrow(ce))
        Vcell[ord, ord] = Matrix(Vr[:, 2:end])
        W = s.details.aggregation_weights
        @test vcov(s) ≈ W * Vcell * W' .* (stderror(s)[1] / per.se[1])^2 rtol = 1e-8
        # Cohort-specific effects.
        sac = did_read_csv("r_sunab_cohort.csv")
        ce = s.details.cohort_effects
        for row in eachrow(sac)
            m = match(r"year__(-?\d+)_cohort__(\d+)", row.term)
            e, g = parse(Int, m[1]), parse(Float64, m[2])
            k = findfirst(i -> ce.e[i] == e && ce.cohort[i] == g, 1:nrow(ce))
            @test ce.estimate[k] ≈ row.estimate atol = 1e-12
            @test ce.std_error[k] ≈ row.se rtol = 1e-3
        end
    end

    @testset "Imputation vs didimputation" begin
        bj = did_read_csv("r_imputation.csv")
        a = did_imputation(mp, :lemp, FirstTreated(:first_treat), :countyreal, :year)
        @test a isa DiDEstimate
        # didimputation's first stage (fixest) is iterative: agreement ~1e-8.
        @test coef(a)[1] ≈ bj.estimate[1] atol = 1e-7
        @test stderror(a)[1] ≈ bj.se[1] rtol = 1e-6
        e = did_imputation(mp, :lemp, FirstTreated(:first_treat), :countyreal, :year;
                           horizons=:all, pretrends=3)
        @test relative_periods(e) == [-3, -2, -1, 0, 1, 2, 3]
        @test coef(e) ≈ bj.estimate[2:end] atol = 1e-7
        post = 4:7
        @test stderror(e)[post] ≈ bj.se[5:end] rtol = 1e-6
        @test stderror(e)[1:3] ≈ bj.se[2:4] rtol = 1e-3     # fixest cluster SEs
        @test coef(e.details.att)[1] ≈ coef(a)[1]
    end

    @testset "Goodman-Bacon vs bacondecomp" begin
        bd = did_read_csv("r_bacon.csv")
        b = bacon_decomposition(mp, :lemp, :d, :countyreal, :year)
        tw = did_read_csv("r_twfe.csv")
        @test b.twfe_estimate ≈ tw.estimate[1] atol = 1e-12
        @test nrow(b.comparisons) == nrow(bd)
        for row in eachrow(bd)
            ctrl = row.untreated == 99999 ? "never treated" : row.untreated
            k = findfirst(i -> b.comparisons.treated[i] == row.treated &&
                               b.comparisons.control[i] == ctrl, 1:nrow(b.comparisons))
            @test k !== nothing
            @test b.comparisons.estimate[k] ≈ row.estimate atol = 1e-12
            @test b.comparisons.weight[k] ≈ row.weight atol = 1e-12
        end
        @test sum(b.comparisons.weight) ≈ 1
    end

    @testset "TWFE weights vs TwoWayFEWeights" begin
        ws = did_read_csv("r_twfe_weights_summary.csv")
        wr = did_read_csv("r_twfe_weights.csv")
        w = twfe_weights(mp, :lemp, :d, :countyreal, :year)
        @test w.beta_fe ≈ ws.beta[1] atol = 1e-12
        @test w.n_negative == ws.nr_minus[1]
        @test w.n_treated_cells == ws.nr_minus[1] + ws.nr_plus[1]
        @test w.sum_negative ≈ ws.sum_minus[1] atol = 1e-10
        @test w.sum_positive ≈ ws.sum_plus[1] atol = 1e-10
        # R divides by the sample SD (n - 1); DrSnow follows the paper's formula.
        n1 = w.n_treated_cells
        @test w.sigma_fe * sqrt((n1 - 1) / n1) ≈ ws.sensibility[1] rtol = 1e-8
        key = Dict((r.unit, r.time) => r.share for r in eachrow(w.weights))
        @test all(r -> key[(r.unit, r.time)] ≈ r.weight, eachrow(wr))
    end
end
