# IV / LATE tests. Monte Carlo checks use `mc_reps(full, fast)` (DRSNOW_SLOW_TESTS).

include("iv_dgps.jl")
include("test_estimator.jl")
include("test_first_stage.jl")
include("test_weak_iv.jl")
include("test_compliance.jl")
include("test_diagnostics.jl")
include("test_sensitivity.jl")
include("test_extrapolation.jl")
include("test_validation.jl")
include("test_kclass_jive.jl")
include("test_validation_manyiv.jl")
include("test_judge.jl")
include("test_shift_share.jl")
include("test_mte.jl")
include("test_huber_mellace.jl")
include("test_weak_iv_robust.jl")
include("test_extrapolation_parametric.jl")
include("test_kitagawa_covariates.jl")
include("test_hhn_cjive.jl")
include("test_rotemberg_panel.jl")
include("test_fll.jl")
include("test_mte_bounds.jl")
include("test_ml_spec_test.jl")
include("test_ml_first_stage.jl")
include("test_multiple_iv_weights.jl")
include("test_dml_lqte.jl")
